server:
  port: 8079

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://www.baidu.com
          order: 0
          predicates:
            - Path=/foo/**
          filters:
            - StripPrefix=1
